---
title: "Домашно задание по СЕМ практикум"
author: " "
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    df_print: paged
    toc: false
    toc_float: true
    number_sections: false
  pdf_document: default
  word_document: default
---

<br>

При решаване на задачите може да използвате вградени функции и команди, които **не** изискват зареждане на пакет или извикване от типа `packageName::fun()`.

<br>


### Задача 1

В тесте от $32$ карти има $4$ маркирани. Тестето е разбъркано и раздадено на $4$ играчи. Чрез подходяща симулация намерете приближение на вероятността на събитието
*"на всеки играч се пада една маркирана карта"*.


### Задача 2

В кутия има $5$ зелени, $7$ сини и $7$ жълти топки. Симулирайте $n$ тегления на топка с връщане. Проверете хипотезата, че в кутията има еднакъв брой топки от трите цвята. Повторете $10000$ пъти за $n=50, 100, 200, 500, 1000$. Колко често заключението на теста е вярно? Представете чрез подходяща графика честотата на вярно заключение в зависимост от $n$.


### Задача 3

В кутия има $5$ зелени, $5$ сини и $5$ жълти топки. Симулирайте $n$ тегления на топка с връщане. Проверете хипотезата, че в кутията има еднакъв брой топки от трите цвята. Повторете $10000$ пъти за $n=50, 100, 200, 500, 1000$. Колко често заключението на теста е вярно?
Представете чрез подходяща графика честотата на вярно заключение в зависимост от $n$.



